## CODE GENERATED BY shinyinputgen: DO NOT EDIT BY HAND

multiUI <- function(id) {
  list(
    checkboxInput(NS(id, "is_male"), "Male", TRUE),
selectInput(NS(id, "KpCalcMethod"), "Kp calculation method", c(
"Poulin and Theil" = "Poulin and Theil",
"Rodgers and Rowland" = "Rodgers and Rowland",
"Berezhkovskiy" = "Berezhkovskiy",
"Schmitt" = "Schmitt",
"PK-Sim" = "PK-Sim")
),
    numericInput(NS(id, "mol_weight"), "molecular weight", 0.456, min = 0, max = 10)
  )
}

moduleServer <- function(id, module) {
  callModule(module, id)
}

multiServer <- function(id) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    is_male <- reactive({
      input$is_male
    })
    KpCalcMethod <- reactive({
      input$KpCalcMethod
    })
    mol_weight <- reactive({
      in_range <- if (input$mol_weight <= 10 && input$mol_weight >= 0) TRUE else FALSE
      shinyFeedback::feedbackDanger(ns('mol_weight'), !in_range,
      sprintf('Numeric value between %s-%s required', 0, 10))
      req(in_range)
      input$mol_weight
    })
    list(
      is_male = is_male,
      KpCalcMethod = KpCalcMethod,
      mol_weight = mol_weight
    )
  })
}