## CODE GENERATED BY shinyinputgen: DO NOT EDIT BY HAND

physioUI <- function(id) {
  list(
    numericInput(NS(id, "molweight"), "molecular weight", 0.456, min = 0, max = 10),
    numericInput(NS(id, "lipo"), "lipophilicity", 1, min = -10, max = 10)
  )
}

moduleServer <- function(id, module) {
  callModule(module, id)
}

physioServer <- function(id) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    molweight <- reactive({
      in_range <- if (input$molweight <= 10 && input$molweight >= 0) TRUE else FALSE
      shinyFeedback::feedbackDanger(ns('molweight'), !in_range,
      sprintf('Numeric value between %s-%s required', 0, 10))
      req(in_range)
      input$molweight
    })
    lipo <- reactive({
      in_range <- if (input$lipo <= 10 && input$lipo >= -10) TRUE else FALSE
      shinyFeedback::feedbackDanger(ns('lipo'), !in_range,
      sprintf('Numeric value between %s-%s required', -10, 10))
      req(in_range)
      input$lipo
    })
    list(
      molweight = molweight,
      lipo = lipo
    )
  })
}