## CODE GENERATED BY shinyinputgen: DO NOT EDIT BY HAND

pkUI <- function(id) {
  list(
    numericInput(NS(id, "vka"), "1st Order Oral Abs rate", 0.456, min = 0, max = 10),
    numericInput(NS(id, "vFa"), "Fraction Absorbed", 1, min = 0, max = 1),
    numericInput(NS(id, "vCL_Ki"), "Renal Clearance", 9.41, min = 0, max = 50)
  )
}

moduleServer <- function(id, module) {
  callModule(module, id)
}

pkServer <- function(id) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns
    vka <- reactive({
      in_range <- if (input$vka <= 10 && input$vka >= 0) TRUE else FALSE
      shinyFeedback::feedbackDanger(ns('vka'), !in_range,
      sprintf('Numeric value between %s-%s required', 0, 10))
      req(in_range)
      input$vka
    })
    vFa <- reactive({
      in_range <- if (input$vFa <= 1 && input$vFa >= 0) TRUE else FALSE
      shinyFeedback::feedbackDanger(ns('vFa'), !in_range,
      sprintf('Numeric value between %s-%s required', 0, 1))
      req(in_range)
      input$vFa
    })
    vCL_Ki <- reactive({
      in_range <- if (input$vCL_Ki <= 50 && input$vCL_Ki >= 0) TRUE else FALSE
      shinyFeedback::feedbackDanger(ns('vCL_Ki'), !in_range,
      sprintf('Numeric value between %s-%s required', 0, 50))
      req(in_range)
      input$vCL_Ki
    })
    list(
      vka = vka,
      vFa = vFa,
      vCL_Ki = vCL_Ki
    )
  })
}