#' generate an input
#' @param .input input list
#' @param .input_name name for input
#' @export
gen_ui_input <- function(.input, .input_name) {
  if (.input$type == "numeric") {
    return(glue::glue('    numericInput(NS(id, "{.input_name}"), "{.input$label}", {.input$value}, min = {.input$min}, max = {.input$max})'))
  }
  if (.input$type == "text") {
    return(glue::glue('    textInput(NS(id, "{.input_name}"), "{.input$label}", {.input$value})'))
  }
  if (.input$type == "checkbox") {
    return(glue::glue('    checkboxInput(NS(id, "{.input_name}"), "{.input$label}", {.input$value})'))
  }
  if (.input$type == "select") {
    vals <- glue::glue_collapse(glue::glue('"{.input$values}" = "{.input$values}"'), sep = ",\n")
    return(glue::glue('    selectInput(NS(id, "{.input_name}"), "{.input$label}", c(\n',
                      vals, ')\n)'))
  }
  stop('type not implemented')
}

#' generate a server reactive
#' @param .input input list
#' @param .input_name name for input
#' @export
gen_server_reactive <- function(.input, .input_name) {
  if (.input$type == "numeric") {
    return(glue::glue("
      {.input_name} <- reactive({{
        in_range <- if (input${.input_name} <= {.input$max} && input${.input_name} >= {.input$min}) {
          TRUE
        } else {
          FALSE
        }
        shinyFeedback::feedbackDanger(ns('{.input_name}'), !in_range,
        sprintf('Numeric value between %s-%s required', {.input$min}, {.input$max}))
        req(in_range)
        input${.input_name}
      }})
  "))
  }
  if (.input$type %in% c("select", "checkbox", "text")) {
    return(glue::glue("
      {.input_name} <- reactive({{
        input${.input_name}
      }})
  "))
  }

  stop("unsupported type")
}

#' code generate a module
#' @param .mt module template list
#' @export
generate_module <- function(.mt) {
  module_name <- .mt$module

  if (is.null(module_name)) {
    stop('must specify a module')
  }

  # clear out module so rest should be inputs
  .mt$module <- NULL
  .mt <- .mt[!is.null(.mt)]



  output_ui <- glue::glue_collapse(
    c(glue::glue("{module_name}UI <- function(id) {{"),
      "  list(" ,
    glue::glue_collapse(purrr::imap(.mt, gen_ui_input), ",\n"),
    "  )",
    "}"
    ), sep = "\n"
  )



  output_server <- glue::glue_collapse(
    c(glue::glue("{module_name}Server <- function(id) {{"),
      "  moduleServer(id, function(input, output, session) {",
      "    ns <- session$ns",
      glue::glue_collapse(purrr::imap(.mt, gen_server_reactive), "\n"),
      "    list(" ,
      glue::glue_collapse(purrr::map(names(.mt), ~ glue::glue('      {.x} = {.x}')), ",\n"),
      "    )",
      "  })",
      "}"
    ), sep = "\n"
  )
  return(list(server = output_server, ui = output_ui, name = module_name, reactives = names(.mt)))
}

write_module <- function(.g, .file) {
  mod_server <- glue::glue("
moduleServer <- function(id, module) {{
  callModule(module, id)
}}
")
  cat("## CODE GENERATED BY shinyinputgen: DO NOT EDIT BY HAND", file = .file)
  cat("\n\n", file = .file, append = TRUE)
  cat(.g$ui, file = .file, append = TRUE)
  cat("\n\n", file = .file, append = TRUE)
  cat(mod_server, file = .file, append = TRUE)
  cat("\n\n", file = .file, append = TRUE)
  cat(.g$server, file = .file, append = TRUE)
}
